version: "3.9"

services:
  career-api:
    build: .
    container_name: career-api
    ports:
      - "8000:8000"
    environment:
      - MODELS_DIR=/app/models
      - OCEAN_URL=https://drive.google.com/uc?id=1vurxZOFd8WFBaRmcWSY5jhJnp8QOUjIk
      - AFFINITY_URL=https://drive.google.com/uc?id=17-fVKTNcQ1m6y_ei8uqlaKb9DiXOsj3h
      - RIASEC_URL=https://drive.google.com/uc?id=14YM8crq4m6P6o11nvX96JOBBibBnnLxf
    restart: unless-stopped
